name: browser-sdk

on:
  push:

jobs:
  browser-sdk-test:
    strategy:
      matrix:
        test_type: [unit, e2e, typecheck]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          repository: 'DataDog/browser-sdk'

      - uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a
        with:
          node-version: 26

      - name: Install dependencies
        run: yarn

      - name: Update rum-events-format
        run: node scripts/json-schemas.ts --update ${{ github.sha }} --build
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: false

      - name: Run ${{matrix.test_type}} tests
        run: |
          case "${{ matrix.test_type }}" in
            unit)
              yarn test:unit
              ;;
            e2e)
              yarn build
              yarn build:apps
              yarn playwright install --with-deps chromium
              yarn test:e2e --workers 10 --project chromium --grep-invert "salesforce"
              ;;
            typecheck)
              yarn typecheck
              ;;
          esac
