name: browser-sdk

on:
  push:

jobs:
  browser-sdk-test:
    strategy:
      matrix:
        test_type: [unit, 'e2e:ci']

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'DataDog/browser-sdk'
          ref: 'thomas.lebeau/rum-event-format-e2e'

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: yarn

      - name: Update rum-events-format
        run: |
          cd rum-events-format
          git checkout ${{ github.sha }}

      - name: Run ${{matrix.test_type}} tests
        run: yarn test:${{matrix.test_type}}
