name: ci

on: [push, pull_request]

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: yarn install
        run: yarn install

      - name: format all files
        run: yarn format

  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install jsonschema
        run: pip install jsonschema

      - name: validate schemas
        run: ./validate.sh
