name: ci

on:
  push:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]

jobs:
  check-is-built:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
      - uses: actions/setup-node@7c12f8017d5436eb855f1ed4399f037a36fbd9e8 # v2.5.2
        with:
          node-version: '20'
      - name: yarn install
        run: yarn install

      - name: yarn build
        run: yarn build

      - name: git status is clean
        shell: bash
        run: |
          [ -z "$(git status --porcelain)" ]

  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
      - uses: actions/setup-node@7c12f8017d5436eb855f1ed4399f037a36fbd9e8 # v2.5.2
        with:
          node-version: '20'
      - name: yarn install
        run: yarn install

      - name: format all files
        run: yarn format

  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
      - uses: actions/setup-node@7c12f8017d5436eb855f1ed4399f037a36fbd9e8 # v2.5.2
        with:
          node-version: '20'
      - name: yarn install
        run: yarn install

      - name: validate script integration tests
        run: node scripts/validate.integration-tests.mjs

      - name: validate schemas
        run: yarn validate
